# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envoke < Formula
  desc "Environment secrets manager with pluggable backends"
  homepage "https://git.dries.info/gerco/Envoke"
  version "0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gerco/envoke/releases/download/v0.2/envoke_0.2_darwin_amd64.tar.gz"
      sha256 "c7de6c476d072c786258dbdb9801dd015aa447195f66d4a535f28b1c571706a2"

      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gerco/envoke/releases/download/v0.2/envoke_0.2_darwin_arm64.tar.gz"
      sha256 "06bf1acd2fe9acbaf1a953c56714ad4302d2bc6e73ea959d1b3f59b6a2accf4d"

      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerco/envoke/releases/download/v0.2/envoke_0.2_linux_amd64.tar.gz"
      sha256 "4a9eb09cbbb3ecd57c550e4113a79dd3c2f0e2f9b1cf1b7ddab7e15d6cb3e82c"
      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerco/envoke/releases/download/v0.2/envoke_0.2_linux_arm64.tar.gz"
      sha256 "0dc13a3430a7230ae17387238ef7bccc6cba8251928a020fea5f79f9f37c467a"
      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envoke version")
    assert_match version.to_s, shell_output("#{bin}/ee version")
  end
end
