# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envoke < Formula
  desc "Environment secrets manager with pluggable backends"
  homepage "https://git.dries.info/gerco/Envoke"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gerco/envoke/releases/download/v0.2.1/envoke_0.2.1_darwin_amd64.tar.gz"
      sha256 "383747c2dba0f1e408e093721b47f3bbc495231b3292e1c3990d12d5c935b6b2"

      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gerco/envoke/releases/download/v0.2.1/envoke_0.2.1_darwin_arm64.tar.gz"
      sha256 "4a619d197d9586c55bdb8be9da46a954651ce407de3af2969701a067f5550027"

      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerco/envoke/releases/download/v0.2.1/envoke_0.2.1_linux_amd64.tar.gz"
      sha256 "65bdc2b2b5e522f1c272fa93b126dc6a4df8e285a135ff853f53326c966f4115"
      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerco/envoke/releases/download/v0.2.1/envoke_0.2.1_linux_arm64.tar.gz"
      sha256 "5c6095a2b8775c896c9c2cbc23e836ae8521ade37fe220634374068690f68010"
      define_method(:install) do
        bin.install "envoke"
        bin.install_symlink "envoke" => "ee"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envoke version")
    assert_match version.to_s, shell_output("#{bin}/ee version")
  end
end
