# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Micdetector < Formula
  desc "Publishes macOS microphone and camera status over MQTT"
  homepage "https://github.com/gerco/MicDetector"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gerco/MicDetector/releases/download/v0.1.3/micdetector_0.1.3_darwin_amd64.tar.gz"
    sha256 "992e34223732eb8d0681990cf10542ee95ce7a2ca5d077d300712e1389fb4f05"

    define_method(:install) do
      bin.install "micdetector"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gerco/MicDetector/releases/download/v0.1.3/micdetector_0.1.3_darwin_arm64.tar.gz"
    sha256 "e63dbe3699a4cd9d0f3d73066916e513587672cccffd6ce3a1c2ce32889d2d74"

    define_method(:install) do
      bin.install "micdetector"
    end
  end

  def caveats
    <<~EOS
      On first start, MicDetector creates a default config file at:
        ~/Library/Application Support/MicDetector/config.json

      Edit it to set your MQTT broker address, then restart:
        brew services restart micdetector

      MicDetector requires microphone and camera permissions.
      Grant access in System Settings > Privacy & Security on first run.

      To view logs:
        log stream --predicate 'subsystem == "com.micdetector"' --style compact
    EOS
  end

  service do
    run [opt_bin/"micdetector"]
    keep_alive successful_exit: false
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micdetector -version")
  end
end
