# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Micdetector < Formula
  desc "Publishes macOS microphone and camera status over MQTT"
  homepage "https://github.com/gerco/MicDetector"
  version "0.2.0-rc2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gerco/MicDetector/releases/download/v0.2.0-rc2/micdetector_0.2.0-rc2_darwin_amd64.tar.gz"
    sha256 "21b0712e730bd501efa430c1d9ce293fd8fdd881799c9ad47f2278012bee89a3"

    define_method(:install) do
      bin.install "micdetector"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gerco/MicDetector/releases/download/v0.2.0-rc2/micdetector_0.2.0-rc2_darwin_arm64.tar.gz"
    sha256 "880b7964c2bd2c8cabc7d036a0eacf90594c8513c370bc2db47f1ddabdc6c772"

    define_method(:install) do
      bin.install "micdetector"
    end
  end

  def caveats
    <<~EOS
      On first start, MicDetector creates a default config file at:
        ~/Library/Application Support/MicDetector/config.json

      Edit it to set your MQTT broker address, then restart:
        brew services restart micdetector

      MicDetector requires microphone and camera permissions.
      Grant access in System Settings > Privacy & Security on first run.

      To view logs:
        log stream --predicate 'subsystem == "com.micdetector"' --style compact
    EOS
  end

  service do
    run [opt_bin/"micdetector"]
    keep_alive successful_exit: false
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micdetector -version")
  end
end
