# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Micdetector < Formula
  desc "Publishes macOS microphone and camera status over MQTT"
  homepage "https://github.com/gerco/MicDetector"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gerco/MicDetector/releases/download/v0.1.2/micdetector_0.1.2_darwin_amd64.tar.gz"
    sha256 "18f2fc6d5afede47386534627c4d222f1be06226d7f7a472f4f655481706e203"

    define_method(:install) do
      bin.install "micdetector"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gerco/MicDetector/releases/download/v0.1.2/micdetector_0.1.2_darwin_arm64.tar.gz"
    sha256 "4f6b59e5d5ec5bc5528ab1838c6dd70e9a41a6a5d0a8170d2a8341877d877c64"

    define_method(:install) do
      bin.install "micdetector"
    end
  end

  def caveats
    <<~EOS
      On first start, MicDetector creates a default config file at:
        ~/Library/Application Support/MicDetector/config.json

      Edit it to set your MQTT broker address, then restart:
        brew services restart micdetector

      MicDetector requires microphone and camera permissions.
      Grant access in System Settings > Privacy & Security on first run.

      To view logs:
        log stream --predicate 'subsystem == "com.micdetector"' --style compact
    EOS
  end

  service do
    run [opt_bin/"micdetector"]
    keep_alive successful_exit: false
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micdetector -version")
  end
end
